CREATE TABLE IF NOT EXISTS t_gift_prisoner_game (
  id INT PRIMARY KEY AUTO_INCREMENT,
  family_id INT NOT NULL,
  room_code VARCHAR(16) NOT NULL,
  room_type VARCHAR(32) NOT NULL DEFAULT 'ROOM',
  host_open_id VARCHAR(128) NOT NULL,
  host_name VARCHAR(128) NOT NULL,
  guest_open_id VARCHAR(128),
  guest_name VARCHAR(128),
  current_round INT NOT NULL DEFAULT 1,
  total_rounds INT NOT NULL DEFAULT 10,
  host_score INT NOT NULL DEFAULT 0,
  guest_score INT NOT NULL DEFAULT 0,
  host_choice VARCHAR(16),
  guest_choice VARCHAR(16),
  winner_open_id VARCHAR(128),
  winner_name VARCHAR(128),
  result_type VARCHAR(32),
  round_history TEXT,
  status VARCHAR(32) NOT NULL DEFAULT 'WAITING',
  started_at DATETIME,
  finished_at DATETIME,
  create_time DATETIME NOT NULL,
  modify_time DATETIME NOT NULL,
  INDEX idx_room_code (room_code),
  INDEX idx_family_status_time (family_id, status, modify_time),
  INDEX idx_host_open_id (host_open_id),
  INDEX idx_guest_open_id (guest_open_id),
  INDEX idx_winner_open_id (winner_open_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
