CREATE TABLE IF NOT EXISTS t_gift_schulte_record (
  id INT PRIMARY KEY AUTO_INCREMENT,
  family_id INT NOT NULL,
  child_id INT NOT NULL,
  child_name VARCHAR(128) NOT NULL,
  child_open_id VARCHAR(128),
  operator_open_id VARCHAR(128) NOT NULL,
  game_name VARCHAR(64) NOT NULL DEFAULT '舒尔特方格',
  game_mode VARCHAR(64) NOT NULL DEFAULT '数字顺序',
  difficulty VARCHAR(16) NOT NULL,
  grid_size INT NOT NULL,
  total_numbers INT NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  duration_ms INT NOT NULL,
  pause_duration_ms INT NOT NULL DEFAULT 0,
  completed TINYINT NOT NULL DEFAULT 1,
  completed_count INT NOT NULL,
  error_count INT NOT NULL DEFAULT 0,
  average_interval_ms INT NOT NULL DEFAULT 0,
  rating VARCHAR(32) NOT NULL,
  note VARCHAR(512),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  create_time DATETIME NOT NULL,
  modify_time DATETIME NOT NULL,
  INDEX idx_family_child_time (family_id, child_id, start_time),
  INDEX idx_family_difficulty_time (family_id, difficulty, start_time),
  INDEX idx_operator_open_id (operator_open_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
